export const HANDLE_NAME = 'HANDLE_NAME'
export const HANDLE_EMAIL = 'HANDLE_EMAIL'
export const HANDLE_PASSWORD = 'HANDLE_PASSWORD'
export const HANDLE_PHONE = 'HANDLE_PHONE'
export const CHANGE_VALUE_PHONE = 'CHANGE_VALUE_PHONE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING'
export const SIGN_UP_LOADING = 'SIGN_UP_LOADING'

// NOTE : CHATS
export const GET_CHATS = 'GET_CHATS'
export const GET_CHAT = 'GET_CHAT'

// NOTE : CONTACTS
export const ADD_CONTACT = 'ADD_CONTACT'
export const ADD_NEW_CONTACT_SUCCESS = 'ADD_NEW_CONTACT_SUCCESS'
export const ADD_NEW_CONTACT_ERROR = 'ADD_NEW_CONTACT_ERROR'
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const CONTACTS_LIST = 'CONTACTS_LIST'

// NOTE : LIST CONVERSATIONS
export const LIST_CONVERSATION_USER = 'LIST_CONVERSATION_USERS'
